name: oceantags
description: "AMRIT mobile app project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0
  geolocator: ^13.0.0
  mobile_scanner: ^6.0.2
  flutter_map: 7.0.2
  image_picker: ^1.1.2
  http: ^1.3.0
  flutter_map_tile_caching: ^10.0.0
  drift: ^2.12.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.11
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.12.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

